export async function getCharactersLeague() {
    // Make sizes for the characters too
    const charactersTemp = [
        {
            id: 1,
            name: 'Aatrox',
            image: 'leagueoflegends/AatroxSquare.webp',
            tags: ['M', 'darkin', 'demonDarkinSpirit', 'godCelestialAspectAscended', 'shurima', 'bruiser', 'top', 'melee', 'manaless', 'AD', 'redEyes', 'naked', 'bald'],
        },
        {
            id: 2,
            name: 'Ahri',
            image: 'leagueoflegends/AhriSquare.webp',
            tags: ['F', 'vastaya', 'ionia', 'mage', 'mid', 'ranged', 'mana', 'AP', 'yellowEyes', 'darkHair', 'longHair', 'animal'],
        },
        {
            id: 3,
            name: 'Akali',
            image: 'leagueoflegends/AkaliSquare.webp',
            tags: ['F', 'human', 'ionia', 'assassin', 'mid', 'melee', 'energy', 'AP', 'redEyes', 'darkHair', 'longHair', 'mask'],
        },
        {
            id: 156,
            name: 'Akshan',
            image: 'leagueoflegends/AkshanSquare.webp',
            tags: ['M', 'human', 'shurima', 'marksman', 'mid', 'ranged', 'mana', 'AD', 'darkEyes', 'darkHair', 'longHair', 'facialHair'],
        },
        {
            id: 4,
            name: 'Alistar',
            image: 'leagueoflegends/AlistarSquare.webp',
            tags: ['M', 'minotaur', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'runeterra', 'tank', 'support', 'melee', 'mana', 'AP', 'redEyes', 'blueHair', 'shortHair', 'facialHair', 'animal'],
        },
        {
            id: 5,
            name: 'Amumu',
            image: 'leagueoflegends/AmumuSquare.webp',
            tags: ['M', 'yordle', 'runeterra', 'tank', 'jungle', 'melee', 'mana', 'AP', 'yellowEyes', 'mask'],
        },
        {
            id: 6,
            name: 'Anivia',
            image: 'leagueoflegends/AniviaSquare.webp',
            tags: ['F', 'god', 'godCelestialAspectAscended', 'freljord', 'mage', 'mid', 'ranged', 'mana', 'AP', 'whiteEyes', 'bald', 'naked', 'animal'],
        },
        {
            id: 7,
            name: 'Annie',
            image: 'leagueoflegends/AnnieSquare.webp',
            tags: ['F', 'human', 'noxus', 'mage', 'mid', 'ranged', 'mana', 'AP', 'greenEyes', 'redHair', 'mediumHair', 'headwear'],
        },
        {
            id: 8,
            name: 'Aphelios',
            image: 'leagueoflegends/ApheliosSquare.webp',
            tags: ['M', 'human', 'lunari', 'targon', 'marksman', 'bot', 'ranged', 'manaless', 'AD', 'darkEyes', 'darkHair', 'mediumHair'],
        },
        {
            id: 9,
            name: 'Ashe',
            image: 'leagueoflegends/AsheSquare.webp',
            tags: ['F', 'iceborne', 'freljord', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'blueEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 10,
            name: 'Aurelion Sol',
            image: 'leagueoflegends/Aurelion_SolSquare.webp',
            tags: ['M', 'dragon', 'god', 'godCelestialAspectAscended', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'targon', 'mage', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'purpleHair', 'longHair', 'headwear', 'naked', 'animal'],
        },
        {
            id: 11,
            name: 'Azir',
            image: 'leagueoflegends/AzirSquare.webp',
            tags: ['M', 'ascended', 'godCelestialAspectAscended', 'shurima', 'mage', 'mid', 'ranged', 'mana', 'AP', 'whiteEyes', 'headwear', 'mask', 'animal'],
        },
        {
            id: 12,
            name: 'Bard',
            image: 'leagueoflegends/BardSquare.webp',
            tags: ['M', 'godCelestialAspectAscended', 'celestial', 'runeterra', 'support', 'bot', 'ranged', 'mana', 'AP', 'yellowEyes', 'bald', 'mask'],
        },
        {
            id: 160,
            name: 'Bel Veth',
            image: 'leagueoflegends/BelvethSquare.webp',
            tags: ['F', 'voidborn', 'void', 'bruiser', 'jungle', 'melee', 'manaless', 'AD', 'purpleEyes', 'purpleHair', 'longHair', 'naked', 'animal'],
        },
        {
            id: 13,
            name: 'Blitzcrank',
            image: 'leagueoflegends/BlitzcrankSquare.webp',
            tags: ['M', 'golem', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'robot', 'zaun', 'tank', 'support', 'bot', 'melee', 'mana', 'AP', 'blueEyes', 'bald', 'robot', 'naked'],
        },
        {
            id: 14,
            name: 'Brand',
            image: 'leagueoflegends/BrandSquare.webp',
            tags: ['M', 'human', 'freljord', 'mage', 'support', 'bot', 'mid', 'ranged', 'mana', 'AP', 'redEyes', 'bald'],
        },
        {
            id: 15,
            name: 'Braum',
            image: 'leagueoflegends/BraumSquare.webp',
            tags: ['M', 'human', 'freljord', 'tank', 'support', 'bot', 'melee', 'mana', 'AP', 'HP-scale', 'darkEyes', 'bald', 'facialHair', 'brownHair'],
        },
        {
            id: 165,
            name: 'Briar',
            image: 'leagueoflegends/BriarSquare.webp',
            tags: ['F', 'golem', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'noxus', 'assassin', 'bruiser', 'jungle', 'melee', 'manaless', 'AD', 'whiteEyes', 'whiteHair', 'longHair'],
        },
        {
            id: 16,
            name: 'Caitlyn',
            image: 'leagueoflegends/CaitlynSquare.webp',
            tags: ['F', 'human', 'piltover', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'blueEyes', 'blueHair', 'longHair', 'headwear'],
        },
        {
            id: 17,
            name: 'Camille',
            image: 'leagueoflegends/CamilleSquare.webp',
            tags: ['F', 'human', 'robot', 'piltover', 'fighter', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'whiteHair', 'mediumHair', 'robot'],
        },
        {
            id: 18,
            name: 'Cassiopeia',
            image: 'leagueoflegends/CassiopeiaSquare.webp',
            tags: ['F', 'human', 'noxus', 'mage', 'mid', 'ranged', 'mana', 'AP', 'yellowEyes', 'animal', 'headwear'],
        },
        {
            id: 19,
            name: 'Cho Gath',
            image: 'leagueoflegends/ChoGathSquare.webp',
            tags: ['M', 'voidborn', 'void', 'runeterra', 'tank', 'top', 'melee', 'mana', 'AP', 'blueEyes', 'bald', 'animal'],
        },
        {
            id: 20,
            name: 'Corki',
            image: 'leagueoflegends/CorkiSquare.webp',
            tags: ['M', 'yordle', 'bandlecity', 'marksman', 'mid', 'ranged', 'mana', 'AP', 'AD', 'Hybrid', 'yellowEyes', 'whiteHair', 'facialHair', 'headwear'],
        },
        {
            id: 21,
            name: 'Darius',
            image: 'leagueoflegends/DariusSquare.webp',
            tags: ['M', 'human', 'noxus', 'fighter', 'top', 'melee', 'manaless', 'AD', 'redEyes', 'darkHair', 'shortHair'],
        },
        {
            id: 22,
            name: 'Diana',
            image: 'leagueoflegends/DianaSquare.webp',
            tags: ['F', 'human', 'godCelestialAspectAscended', 'lunari', 'targon', 'assassin', 'mid', 'melee', 'mana', 'AP', 'whiteEyes', 'whiteHair', 'longHair'],
        },
        {
            id: 23,
            name: 'Dr. Mundo',
            image: 'leagueoflegends/Dr._MundoSquare.webp',
            tags: ['M', 'human', 'zaun', 'tank', 'top', 'melee', 'health', 'otherResource', 'HP-scale', 'purpleEyes', 'darkHair', 'shortHair'],
        },
        {
            id: 24,
            name: 'Draven',
            image: 'leagueoflegends/DravenSquare.webp',
            tags: ['M', 'human', 'noxus', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'blueEyes', 'brownHair', 'mediumHair', 'facialHair', 'headwear'],
        },
        {
            id: 25,
            name: 'Ekko',
            image: 'leagueoflegends/EkkoSquare.webp',
            tags: ['M', 'human', 'zaun', 'assassin', 'mid', 'melee', 'mana', 'AP', 'darkEyes', 'whiteHair', 'mediumHair'],
        },
        {
            id: 26,
            name: 'Elise',
            image: 'leagueoflegends/EliseSquare.webp',
            tags: ['F', 'human', 'noxus', 'shadow-isles', 'mage', 'jungle', 'ranged', 'mana', 'AP', 'redEyes', 'animal', 'headwear'],
        },
        {
            id: 27,
            name: 'Evelynn',
            image: 'leagueoflegends/EvelynnSquare.webp',
            tags: ['F', 'demon', 'demonDarkinSpirit', 'runeterra', 'assassin', 'jungle', 'melee', 'mana', 'AP', 'yellowEyes', 'whiteHair', 'longHair'],
        },
        {
            id: 28,
            name: 'Ezreal',
            image: 'leagueoflegends/EzrealSquare.webp',
            tags: ['M', 'human', 'piltover', 'marksman', 'bot', 'ranged', 'mana', 'AP', 'AD', 'Hybrid', 'blueEyes', 'blondeHair', 'mediumHair', 'headwear'],
        },
        {
            id: 29,
            name: 'Fiddlesticks',
            image: 'leagueoflegends/FiddlesticksSquare.webp',
            tags: ['M', 'demon', 'demonDarkinSpirit', 'runeterra', 'mage', 'support', 'jungle', 'ranged', 'mana', 'AP', 'yellowEyes', 'bald'],
        },
        {
            id: 30,
            name: 'Fiora',
            image: 'leagueoflegends/FioraSquare.webp',
            tags: ['F', 'human', 'demacia', 'fighter', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'purpleHair', 'mediumHair'],
        },
        {
            id: 31,
            name: 'Fizz',
            image: 'leagueoflegends/FizzSquare.webp',
            tags: ['M', 'yordle', 'bilgewater', 'assassin', 'mid', 'melee', 'mana', 'AP', 'greenEyes', 'bald', 'naked', 'animal'],
        },
        {
            id: 32,
            name: 'Galio',
            image: 'leagueoflegends/GalioSquare.webp',
            tags: ['M', 'golem', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'demacia', 'tank', 'support', 'mid', 'melee', 'mana', 'AP', 'darkEyes', 'bald', 'headwear', 'naked'],
        },
        {
            id: 33,
            name: 'Gangplank',
            image: 'leagueoflegends/GangplankSquare.webp',
            tags: ['M', 'human', 'bilgewater', 'fighter', 'top', 'melee', 'mana', 'AD', 'darkEyes', 'darkHair', 'facialHair', 'headwear'],
        },
        {
            id: 34,
            name: 'Garen',
            image: 'leagueoflegends/GarenSquare.webp',
            tags: ['M', 'human', 'demacia', 'fighter', 'top', 'melee', 'manaless', 'AD', 'blueEyes', 'brownHair', 'shortHair'],
        },
        {
            id: 35,
            name: 'Gnar',
            image: 'leagueoflegends/GnarSquare.webp',
            tags: ['M', 'yordle', 'freljord', 'fighter', 'top', 'ranged', 'melee', 'rage', 'otherResource', 'AD', 'darkEyes', 'orangeHair', 'shortHair', 'headwear', 'animal'],
        },
        {
            id: 36,
            name: 'Gragas',
            image: 'leagueoflegends/GragasSquare.webp',
            tags: ['M', 'human', 'freljord', 'tank', 'jungle', 'melee', 'mana', 'AP', 'blueEyes', 'orangeHair', 'longHair', 'facialHair'],
        },
        {
            id: 37,
            name: 'Graves',
            image: 'leagueoflegends/GravesSquare.webp',
            tags: ['M', 'human', 'bilgewater', 'marksman', 'jungle', 'ranged', 'mana', 'AD', 'blueEyes', 'darkHair', 'shortHair', 'facialHair'],
        },
        {
            id: 155,
            name: 'Gwen',
            image: 'leagueoflegends/GwenSquare.webp',
            tags: ['F', 'spirit', 'demon', 'camavor', 'icathiaKathkanCamavor', 'shadow-isles', 'fighter', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'pinkEyes', 'blueHair', 'longHair', 'headwear'],
        },
        {
            id: 38,
            name: 'Hecarim',
            image: 'leagueoflegends/HecarimSquare.webp',
            tags: ['M', 'shadow-isles', 'camavor', 'icathiaKathkanCamavor', 'fighter', 'jungle', 'melee', 'mana', 'AD', 'blueEyes', 'bald', 'animal', 'naked'],
        },
        {
            id: 39,
            name: 'Heimerdinger',
            image: 'leagueoflegends/HeimerdingerSquare.webp',
            tags: ['M', 'yordle', 'piltover', 'mage', 'top', 'ranged', 'mana', 'AP', 'blueEyes', 'blondeHair', 'longHair', 'animal', 'headwear', 'facialHair'],
        },
        {
            id: 166,
            name: 'Hwei',
            image: 'leagueoflegends/HweiSquare.webp',
            tags: ['M', 'human', 'ionia', 'mage', 'mid', 'support', 'ranged', 'mana', 'AP', 'redEyes', 'greenHair', 'mediumHair'],
        },
        {
            id: 40,
            name: 'Illaoi',
            image: 'leagueoflegends/IllaoiSquare.webp',
            tags: ['F', 'human', 'bilgewater', 'fighter', 'top', 'melee', 'mana', 'AD', 'greenEyes', 'brownHair', 'longHair'],
        },
        {
            id: 41,
            name: 'Irelia',
            image: 'leagueoflegends/IreliaSquare.webp',
            tags: ['F', 'human', 'ionia', 'fighter', 'mid', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'blueHair', 'longHair', 'headwear'],
        },
        {
            id: 42,
            name: 'Ivern',
            image: 'leagueoflegends/IvernSquare.webp',
            tags: ['M', 'tree', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'ionia', 'freljord', 'support', 'jungle', 'mana', 'AP', 'orangeEyes', 'bald', 'naked'],
        },
        {
            id: 43,
            name: 'Janna',
            image: 'leagueoflegends/JannaSquare.webp',
            tags: ['F', 'god', 'godCelestialAspectAscended', 'zaun', 'shurima', 'support', 'ranged', 'mana', 'AP', 'blueEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 44,
            name: 'Jarvan IV',
            image: 'leagueoflegends/Jarvan_IVSquare.webp',
            tags: ['M', 'human', 'demacia', 'tank', 'jungle', 'melee', 'mana', 'AD', 'blueEyes', 'headwear'],
        },
        {
            id: 45,
            name: 'Jax',
            image: 'leagueoflegends/JaxSquare.webp',
            tags: ['M', 'icathia', 'icathiaKathkanCamavor', 'shurima', 'fighter', 'top', 'melee', 'mana', 'AP', 'AD', 'Hybrid', 'blueEyes', 'mask', 'headwear'],
        },
        {
            id: 46,
            name: 'Jayce',
            image: 'leagueoflegends/JayceSquare.webp',
            tags: ['M', 'human', 'piltover', 'fighter', 'top', 'ranged', 'mana', 'AD', 'blueEyes', 'brownHair', 'shortHair'],
        },
        {
            id: 47,
            name: 'Jhin',
            image: 'leagueoflegends/JhinSquare.webp',
            tags: ['M', 'human', 'ionia', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'redEyes', 'headwear', 'mask'],
        },
        {
            id: 48,
            name: 'Jinx',
            image: 'leagueoflegends/JinxSquare.webp',
            tags: ['F', 'human', 'zaun', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'pinkEyes', 'blueHair', 'longHair'],
        },
        {
            id: 49,
            name: 'Kai Sa',
            image: 'leagueoflegends/KaiSaSquare.webp',
            tags: ['F', 'human', 'void', 'shurima', 'marksman', 'bot', 'ranged', 'mana', 'AP', 'AD', 'Hybrid', 'purpleEyes', 'purpleHair', 'longHair'],
        },
        {
            id: 50,
            name: 'Kalista',
            image: 'leagueoflegends/KalistaSquare.webp',
            tags: ['F', 'undead', 'shadow-isles', 'camavor', 'icathiaKathkanCamavor', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'blueEyes', 'darkHair', 'longHair', 'headwear'],
        },
        {
            id: 51,
            name: 'Karma',
            image: 'leagueoflegends/KarmaSquare.webp',
            tags: ['F', 'human', 'ionia', 'mage', 'support', 'mid', 'ranged', 'mana', 'AP', 'pinkEyes', 'brownHair', 'shortHair', 'headwear'],
        },
        {
            id: 52,
            name: 'Karthus',
            image: 'leagueoflegends/KarthusSquare.webp',
            tags: ['M', 'undead', 'shadow-isles', 'mage', 'mid', 'bot', 'ranged', 'mana', 'AP', 'blueEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 53,
            name: 'Kassadin',
            image: 'leagueoflegends/KassadinSquare.webp',
            tags: ['M', 'human', 'void', 'shurima', 'mage', 'mid', 'melee', 'mana', 'AP', 'yellowEyes', 'headwear', 'mask'],
        },
        {
            id: 54,
            name: 'Katarina',
            image: 'leagueoflegends/KatarinaSquare.webp',
            tags: ['F', 'human', 'noxus', 'assassin', 'mid', 'melee', 'manaless', 'AP', 'AD', 'Hybrid', 'greenEyes', 'redHair', 'longHair'],
        },
        {
            id: 55,
            name: 'Kayle',
            image: 'leagueoflegends/KayleSquare.webp',
            tags: ['F', 'aspect', 'godCelestialAspectAscended', 'targon', 'demacia', 'fighter', 'top', 'ranged', 'mana', 'AP', 'yellowEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 56,
            name: 'Kayn',
            image: 'leagueoflegends/KaynSquare.webp',
            tags: ['M', 'human', 'darkin', 'demonDarkinSpirit', 'shurima', 'ionia', 'noxus', 'assassin', 'bruiser', 'jungle', 'melee', 'mana', 'AD', 'redEyes', 'darkEyes', 'darkHair', 'blueHair', 'longHair'],
        },
        {
            id: 57,
            name: 'Kennen',
            image: 'leagueoflegends/KennenSquare.webp',
            tags: ['M', 'yordle', 'ionia', 'bandlecity', 'mage', 'top', 'ranged', 'energy', 'AP', 'blueEyes', 'brownHair', 'shortHair', 'headwear', 'mask', 'animal'],
        },
        {
            id: 58,
            name: 'Kha Zix',
            image: 'leagueoflegends/KhaZixSquare.webp',
            tags: ['M', 'voidborn', 'void', 'assassin', 'jungle', 'melee', 'mana', 'AD', 'greenEyes', 'bald', 'animal', 'naked'],
        },
        {
            id: 59,
            name: 'Kindred',
            image: 'leagueoflegends/KindredSquare.webp',
            tags: ['M', 'F', 'spirit', 'demonDarkinSpirit', 'runeterra', 'marksman', 'jungle', 'ranged', 'mana', 'AD', 'blueEyes', 'whiteHair', 'darkHair', 'mediumHair', 'longHair', 'mask', 'animal', 'naked'],
        },
        {
            id: 60,
            name: 'Kled',
            image: 'leagueoflegends/KledSquare.webp',
            tags: ['M', 'yordle', 'noxus', 'fighter', 'top', 'melee', 'manaless', 'courage', 'otherResource', 'AD', 'redEyes', 'darkEyes', 'whiteHair', 'mediumHair', 'facialHair', 'headwear', 'animal'],
        },
        {
            id: 61,
            name: 'Kog Maw',
            image: 'leagueoflegends/KogMawSquare.webp',
            tags: ['M', 'void', 'marksman', 'bot', 'ranged', 'mana', 'AP', 'AD', 'Hybrid', 'redEyes', 'bald', 'animal', 'naked'],
        },
        {
            id: 162,
            name: 'K Sante',
            image: 'leagueoflegends/KSanteSquare.webp',
            tags: ['M', 'human', 'shurima', 'tank', 'bruiser', 'assassin', 'top', 'melee', 'mana', 'AD', 'orangeEyes', 'brownHair', 'shortHair', 'facialHair'],
        },
        {
            id: 62,
            name: 'LeBlanc',
            image: 'leagueoflegends/LeBlancSquare.webp',
            tags: ['F', 'human', 'noxus', 'mage', 'mid', 'ranged', 'mana', 'AP', 'yellowEyes', 'darkHair', 'mediumHair', 'headwear'],
        },
        {
            id: 63,
            name: 'Lee Sin',
            image: 'leagueoflegends/Lee_SinSquare.webp',
            tags: ['M', 'human', 'ionia', 'fighter', 'jungle', 'melee', 'energy', 'AD', 'brownHair', 'longHair', 'mask', 'facialHair'],
        },
        {
            id: 64,
            name: 'Leona',
            image: 'leagueoflegends/LeonaSquare.webp',
            tags: ['F', 'human', 'solari', 'godCelestialAspectAscended', 'targon', 'tank', 'support', 'melee', 'mana', 'AP', 'orangeEyes', 'brownHair', 'longHair', 'headwear'],
        },
        {
            id: 65,
            name: 'Lillia',
            image: 'leagueoflegends/LilliaSquare.webp',
            tags: ['F', 'spirit', 'demonDarkinSpirit', 'ionia', 'fighter', 'jungle', 'melee', 'mana', 'AP', 'blueEyes', 'pinkEyes', 'blueHair', 'pinkHair', 'longHair', 'headwear', 'animal'],
        },
        {
            id: 66,
            name: 'Lissandra',
            image: 'leagueoflegends/LissandraSquare.webp',
            tags: ['F', 'iceborne', 'freljord', 'mage', 'mid', 'ranged', 'mana', 'AP', 'headwear', 'mask'],
        },
        {
            id: 67,
            name: 'Lucian',
            image: 'leagueoflegends/LucianSquare.webp',
            tags: ['M', 'human', 'demacia', 'shadow-isles', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'greenEyes', 'brownHair', 'longHair'],
        },
        {
            id: 68,
            name: 'Lulu',
            image: 'leagueoflegends/LuluSquare.webp',
            tags: ['F', 'yordle', 'bandlecity', 'mage', 'support', 'ranged', 'mana', 'AP', 'greenEyes', 'purpleHair', 'longHair', 'headwear'],
        },
        {
            id: 69,
            name: 'Lux',
            image: 'leagueoflegends/LuxSquare.webp',
            tags: ['F', 'human', 'demacia', 'mage', 'support', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'blondeHair', 'longHair'],
        },
        {
            id: 70,
            name: 'Malphite',
            image: 'leagueoflegends/MalphiteSquare.webp',
            tags: ['M', 'golem', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'ixtal', 'tank', 'top', 'melee', 'mana', 'AP', 'greenEyes', 'bald', 'naked'],
        },
        {
            id: 71,
            name: 'Malzahar',
            image: 'leagueoflegends/MalzaharSquare.webp',
            tags: ['M', 'human', 'void', 'shurima', 'mage', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'headwear', 'mask'],
        },
        {
            id: 72,
            name: 'Maokai',
            image: 'leagueoflegends/MaokaiSquare.webp',
            tags: ['M', 'tree', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'shadow-isles', 'tank', 'top', 'melee', 'mana', 'AP', 'blueEyes', 'naked'],
        },
        {
            id: 73,
            name: 'Master Yi',
            image: 'leagueoflegends/Master_YiSquare.webp',
            tags: ['M', 'human', 'ionia', 'assassin', 'jungle', 'melee', 'mana', 'AD', 'facialHair', 'facialHair', 'mask'],
        },
        {
            id: 163,
            name: 'Milio',
            image: 'leagueoflegends/MilioSquare.webp',
            tags: ['M', 'human', 'ixtal', 'enchanter', 'support', 'ranged', 'mana', 'AP', 'orangeEyes', 'brownHair', 'mediumHair'],
        },
        {
            id: 74,
            name: 'Miss Fortune',
            image: 'leagueoflegends/MissFortuneSquare.webp',
            tags: ['F', 'human', 'bilgewater', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'blueEyes', 'redHair', 'longHair', 'headwear'],
        },
        {
            id: 75,
            name: 'Mordekaiser',
            image: 'leagueoflegends/MordekaiserSquare.webp',
            tags: ['M', 'undead', 'demonDarkinSpirit', 'shadow-isles', 'fighter', 'top', 'melee', 'shield', 'otherResource', 'AP', 'greenEyes', 'headwear'],
        },
        {
            id: 76,
            name: 'Morgana',
            image: 'leagueoflegends/MorganaSquare.webp',
            tags: ['F', 'aspect', 'godCelestialAspectAscended', 'runeterra', 'mage', 'support', 'mid', 'ranged', 'mana', 'AP', 'pinkEyes', 'purpleHair', 'longHair'],
        },
        {
            id: 164,
            name: 'Naafiri',
            image: 'leagueoflegends/NaafiriSquare.webp',
            tags: ['F', 'darkin', 'demonDarkinSpirit', 'dog', 'dawg-wit-de-butta-on-im', 'shurima', 'assassin', 'mid', 'melee', 'mana', 'AD', 'redEyes', 'animal', 'naked'],
        },
        {
            id: 77,
            name: 'Nami',
            image: 'leagueoflegends/NamiSquare.webp',
            tags: ['F', 'vastaya', 'bilgewater', 'support', 'bot', 'ranged', 'mana', 'AP', 'orangeEyes', 'bald', 'animal', 'naked', 'headwear'],
        },
        {
            id: 78,
            name: 'Nasus',
            image: 'leagueoflegends/NasusSquare.webp',
            tags: ['M', 'ascended', 'godCelestialAspectAscended', 'shurima', 'fighter', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'brownHair', 'shortHair', 'animal', 'headwear'],
        },
        {
            id: 79,
            name: 'Nautilus',
            image: 'leagueoflegends/NautilusSquare.webp',
            tags: ['M', 'titan', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'bilgewater', 'tank', 'support', 'bot', 'melee', 'mana', 'AP', 'orangeEyes', 'mask', 'headwear'],
        },
        {
            id: 80,
            name: 'Neeko',
            image: 'leagueoflegends/NeekoSquare.webp',
            tags: ['F', 'vastaya', 'runeterra', 'mage', 'mid', 'ranged', 'mana', 'AP', 'orangeEyes', 'purpleHair', 'pinkHair', 'longHair', 'animal'],
        },
        {
            id: 81,
            name: 'Nidalee',
            image: 'leagueoflegends/NidaleeSquare.webp',
            tags: ['F', 'vastaya', 'ixtal', 'assassin', 'jungle', 'ranged', 'melee', 'mana', 'AP', 'greenEyes', 'brownHair', 'longHair', 'animal'],
        },
        {
            id: 161,
            name: 'Nilah',
            image: 'leagueoflegends/NilahSquare.webp',
            tags: ['F', 'human', 'bilgewater', 'kathkan', 'icathiaKathkanCamavor', 'bruiser', 'bot', 'melee', 'mana', 'AD', 'blueEyes', 'darkHair', 'longHair'],
        },
        {
            id: 82,
            name: 'Nocturne',
            image: 'leagueoflegends/NocturneSquare.webp',
            tags: ['M', 'demon', 'demonDarkinSpirit', 'runeterra', 'assassin', 'jungle', 'melee', 'mana', 'AD', 'whiteEyes', 'bald', 'naked'],
        },
        {
            id: 83,
            name: 'Nunu & Willump',
            image: 'leagueoflegends/Nunu&WillumpSquare.webp',
            tags: ['M', 'human', 'yeti', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'freljord', 'tank', 'jungle', 'melee', 'mana', 'AP', 'blueEyes', 'darkHair', 'whiteHair', 'blueHair', 'mediumHair', 'facialHair', 'headwear', 'animal', 'naked', 'headwear'],
        },
        {
            id: 84,
            name: 'Olaf',
            image: 'leagueoflegends/OlafSquare.webp',
            tags: ['M', 'human', 'freljord', 'fighter', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'orangeHair', 'longHair', 'facialHair', 'headwear'],
        },
        {
            id: 85,
            name: 'Orianna',
            image: 'leagueoflegends/OriannaSquare.webp',
            tags: ['F', 'golem', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'piltover', 'mage', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'brownHair', 'mediumHair', 'naked', 'robot'],
        },
        {
            id: 86,
            name: 'Ornn',
            image: 'leagueoflegends/OrnnSquare.webp',
            tags: ['M', 'god', 'godCelestialAspectAscended', 'freljord', 'tank', 'top', 'melee', 'mana', 'AP', 'redEyes', 'redHair', 'mediumHair', 'facialHair', 'animal'],
        },
        {
            id: 87,
            name: 'Pantheon',
            image: 'leagueoflegends/PantheonSquare.webp',
            tags: ['M', 'human', 'aspect', 'godCelestialAspectAscended', 'targon', 'fighter', 'top', 'melee', 'mana', 'AD', 'orangeEyes', 'brownHair', 'shortHair', 'headwear', 'mask', 'facialHair'],
        },
        {
            id: 88,
            name: 'Poppy',
            image: 'leagueoflegends/PoppySquare.webp',
            tags: ['F', 'yordle', 'demacia', 'bandlecity', 'tank', 'top', 'melee', 'mana', 'AD', 'pinkEyes', 'blondeHair', 'longHair'],
        },
        {
            id: 89,
            name: 'Pyke',
            image: 'leagueoflegends/PykeSquare.webp',
            tags: ['M', 'undead', 'bilgewater', 'assassin', 'support', 'melee', 'mana', 'AD', 'blueEyes', 'bald', 'mask'],
        },
        {
            id: 90,
            name: 'Qiyana',
            image: 'leagueoflegends/QiyanaSquare.webp',
            tags: ['F', 'human', 'ixtal', 'assassin', 'mid', 'melee', 'mana', 'AD', 'yellowEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 91,
            name: 'Quinn',
            image: 'leagueoflegends/QuinnSquare.webp',
            tags: ['F', 'human', 'demacia', 'marksman', 'top', 'ranged', 'mana', 'AD', 'orangeEyes', 'headwear'],
        },
        {
            id: 92,
            name: 'Rakan',
            image: 'leagueoflegends/RakanSquare.webp',
            tags: ['M', 'vastaya', 'ionia', 'support', 'bot', 'melee', 'mana', 'AP', 'blueEyes', 'whiteHair', 'redHair', 'mediumHair', 'animal', 'facialHair'],
        },
        {
            id: 93,
            name: 'Rammus',
            image: 'leagueoflegends/RammusSquare.webp',
            tags: ['M', 'god', 'godCelestialAspectAscended', 'shurima', 'tank', 'jungle', 'melee', 'mana', 'AP', 'orangeEyes', 'bald', 'animal', 'naked'],
        },
        {
            id: 94,
            name: 'Rek Sai',
            image: 'leagueoflegends/RekSaiSquare.webp',
            tags: ['F', 'void', 'shurima', 'fighter', 'jungle', 'melee', 'fury', 'otherResource', 'AD', 'bald', 'animal', 'naked'],
        },
        {
            id: 95,
            name: 'Rell',
            image: 'leagueoflegends/RellSquare.webp',
            tags: ['F', 'human', 'noxus', 'tank', 'support', 'jungle', 'melee', 'mana', 'AP', 'orangeEyes', 'blondeHair', 'brownHair', 'longHair'],
        },
        {
            id: 159,
            name: 'Renata Glasc',
            image: 'leagueoflegends/RenataSquare.webp',
            tags: ['F', 'human', 'zaun', 'support', 'ranged', 'mana', 'AP', 'pinkEyes', 'whiteHair', 'darkHair', 'longHair', 'mask'],
        },
        {
            id: 96,
            name: 'Renekton',
            image: 'leagueoflegends/RenektonSquare.webp',
            tags: ['M', 'ascended', 'godCelestialAspectAscended', 'shurima', 'fighter', 'top', 'melee', 'fury', 'otherResource', 'AD', 'orangeEyes', 'bald', 'animal', 'headwear'],
        },
        {
            id: 97,
            name: 'Rengar',
            image: 'leagueoflegends/RengarSquare.webp',
            tags: ['M', 'vastaya', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'ixtal', 'assassin', 'jungle', 'melee', 'ferocity', 'otherResource', 'AD', 'blueEyes', 'orangeEyes', 'whiteHair', 'longHair', 'headwear', 'mask', 'animal', 'cat'],
        },
        {
            id: 98,
            name: 'Riven',
            image: 'leagueoflegends/RivenSquare.webp',
            tags: ['F', 'human', 'noxus', 'fighter', 'top', 'melee', 'manaless', 'AD', 'orangeEyes', 'whiteHair', 'mediumHair'],
        },
        {
            id: 99,
            name: 'Rumble',
            image: 'leagueoflegends/RumbleSquare.webp',
            tags: ['M', 'yordle', 'piltover', 'bandlecity', 'fighter', 'top', 'melee', 'heat', 'otherResource', 'AP', 'orangeEyes', 'blueHair', 'mediumHair', 'headwear', 'animal'],
        },
        {
            id: 100,
            name: 'Ryze',
            image: 'leagueoflegends/RyzeSquare.webp',
            tags: ['M', 'human', 'runeterra', 'mage', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'bald', 'brownHair', 'facialHair'],
        },
        {
            id: 101,
            name: 'Samira',
            image: 'leagueoflegends/SamiraSquare.webp',
            tags: ['F', 'human', 'noxus', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'greenEyes', 'brownHair', 'longHair', 'mask'],
        },
        {
            id: 102,
            name: 'Sejuani',
            image: 'leagueoflegends/SejuaniSquare.webp',
            tags: ['F', 'iceborne', 'freljord', 'tank', 'jungle', 'melee', 'mana', 'AP', 'blueEyes', 'whiteHair', 'shortHair', 'headwear'],
        },
        {
            id: 103,
            name: 'Senna',
            image: 'leagueoflegends/SennaSquare.webp',
            tags: ['F', 'undead', 'demacia', 'shadow-isles', 'marksman', 'support', 'bot', 'ranged', 'mana', 'AD', 'greenEyes', 'darkHair', 'longHair', 'headwear'],
        },
        {
            id: 104,
            name: 'Seraphine',
            image: 'leagueoflegends/SeraphineSquare.webp',
            tags: ['F', 'human', 'piltover', 'mage', 'support', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'pinkHair', 'longHair'],
        },
        {
            id: 105,
            name: 'Sett',
            image: 'leagueoflegends/SettSquare.webp',
            tags: ['M', 'human', 'vastaya', 'ionia', 'noxus', 'fighter', 'top', 'melee', 'grit', 'otherResource', 'AD', 'orangeEyes', 'redHair', 'mediumHair', 'animal'],
        },
        {
            id: 106,
            name: 'Shaco',
            image: 'leagueoflegends/ShacoSquare.webp',
            tags: ['M', 'demon', 'demonDarkinSpirit', 'runeterra', 'assassin', 'jungle', 'melee', 'mana', 'AP', 'AD', 'Hybrid', 'purpleEyes', 'bald', 'headwear'],
        },
        {
            id: 107,
            name: 'Shen',
            image: 'leagueoflegends/ShenSquare.webp',
            tags: ['M', 'human', 'ionia', 'tank', 'top', 'melee', 'energy', 'AP', 'blueEyes', 'brownHair', 'shortHair', 'mask', 'headwear'],
        },
        {
            id: 108,
            name: 'Shyvana',
            image: 'leagueoflegends/ShyvanaSquare.webp',
            tags: ['F', 'dragon', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'demacia', 'fighter', 'jungle', 'melee', 'fury', 'otherResource', 'AP', 'AD', 'Hybrid', 'orangeEyes', 'purpleHair', 'longHair', 'headwear', 'animal'],
        },
        {
            id: 109,
            name: 'Singed',
            image: 'leagueoflegends/SingedSquare.webp',
            tags: ['M', 'human', 'zaun', 'tank', 'top', 'melee', 'mana', 'AP', 'greenEyes', 'bald', 'mask'],
        },
        {
            id: 110,
            name: 'Sion',
            image: 'leagueoflegends/SionSquare.webp',
            tags: ['M', 'undead', 'noxus', 'tank', 'top', 'melee', 'mana', 'AD', 'redEyes', 'bald', 'headwear', 'mask'],
        },
        {
            id: 111,
            name: 'Sivir',
            image: 'leagueoflegends/SivirSquare.webp',
            tags: ['F', 'human', 'shurima', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'blueEyes', 'brownHair', 'longHair', 'headwear'],
        },
        {
            id: 112,
            name: 'Skarner',
            image: 'leagueoflegends/SkarnerSquare.webp',
            tags: ['M', 'brackern', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'ixtal', 'fighter', 'jungle', 'melee', 'mana', 'AD', 'yellowEyes', 'bald', 'animal', 'naked'],
        },
        {
            id: 113,
            name: 'Sona',
            image: 'leagueoflegends/SonaSquare.webp',
            tags: ['F', 'human', 'demacia', 'support', 'ranged', 'mana', 'AP', 'blueEyes', 'blueHair', 'longHair'],
        },
        {
            id: 114,
            name: 'Soraka',
            image: 'leagueoflegends/SorakaSquare.webp',
            tags: ['F', 'celestial', 'godCelestialAspectAscended', 'targon', 'support', 'ranged', 'mana', 'AP', 'orangeEyes', 'whiteHair', 'longHair', 'animal'],
        },
        {
            id: 115,
            name: 'Swain',
            image: 'leagueoflegends/SwainSquare.webp',
            tags: ['M', 'human', 'noxus', 'mage', 'mid', 'ranged', 'mana', 'AP', 'redEyes', 'whiteHair', 'mediumHair'],
        },
        {
            id: 116,
            name: 'Sylas',
            image: 'leagueoflegends/SylasSquare.webp',
            tags: ['M', 'human', 'demacia', 'mage', 'mid', 'melee', 'mana', 'AP', 'blueEyes', 'darkHair', 'mediumHair', 'facialHair'],
        },
        {
            id: 117,
            name: 'Syndra',
            image: 'leagueoflegends/SyndraSquare.webp',
            tags: ['F', 'human', 'ionia', 'mage', 'mid', 'ranged', 'mana', 'AP', 'purpleEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 118,
            name: 'Tahm Kench',
            image: 'leagueoflegends/Tahm_KenchSquare.webp',
            tags: ['M', 'demon', 'demonDarkinSpirit', 'bilgewater', 'runeterra', 'tank', 'support', 'top', 'melee', 'mana', 'AP', 'yellowEyes', 'bald', 'animal', 'headwear'],
        },
        {
            id: 119,
            name: 'Taliyah',
            image: 'leagueoflegends/TaliyahSquare.webp',
            tags: ['F', 'human', 'shurima', 'mage', 'mid', 'jungle', 'ranged', 'mana', 'AP', 'brownEyes', 'brownHair', 'mediumHair', 'headwear'],
        },
        {
            id: 120,
            name: 'Talon',
            image: 'leagueoflegends/TalonSquare.webp',
            tags: ['M', 'human', 'noxus', 'assassin', 'mid', 'melee', 'mana', 'AD', 'yellowEyes', 'darkHair', 'mediumHair', 'headwear'],
        },
        {
            id: 121,
            name: 'Taric',
            image: 'leagueoflegends/TaricSquare.webp',
            tags: ['M', 'aspect', 'godCelestialAspectAscended', 'targon', 'demacia', 'tank', 'support', 'melee', 'mana', 'AP', 'blueEyes', 'brownHair', 'longHair'],
        },
        {
            id: 122,
            name: 'Teemo',
            image: 'leagueoflegends/TeemoSquare.webp',
            tags: ['M', 'yordle', 'bandlecity', 'marksman', 'top', 'ranged', 'mana', 'AP', 'orangeHair', 'shortHair', 'headwear', 'mask', 'animal'],
        },
        {
            id: 123,
            name: 'Thresh',
            image: 'leagueoflegends/ThreshSquare.webp',
            tags: ['M', 'undead', 'shadow-isles', 'support', 'ranged', 'mana', 'AP', 'greenEyes', 'bald'],
        },
        {
            id: 124,
            name: 'Tristana',
            image: 'leagueoflegends/TristanaSquare.webp',
            tags: ['F', 'yordle', 'bandlecity', 'marksman', 'bot', 'mid', 'ranged', 'mana', 'AD', 'orangeEyes', 'whiteHair', 'shortHair', 'mask'],
        },
        {
            id: 125,
            name: 'Trundle',
            image: 'leagueoflegends/TrundleSquare.webp',
            tags: ['M', 'troll', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'freljord', 'fighter', 'jungle', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'RedHair', 'mediumHair', 'facialHair'],
        },
        {
            id: 126,
            name: 'Tryndamere',
            image: 'leagueoflegends/TryndamereSquare.webp',
            tags: ['M', 'human', 'freljord', 'fighter', 'top', 'melee', 'fury', 'otherResource', 'AD', 'blueEyes', 'darkHair', 'mediumHair', 'headwear', 'facialHair'],
        },
        {
            id: 127,
            name: 'Twisted Fate',
            image: 'leagueoflegends/Twisted_FateSquare.webp',
            tags: ['M', 'human', 'bilgewater', 'mage', 'mid', 'ranged', 'mana', 'AP', 'AD', 'Hybrid', 'blueEyes', 'brownHair', 'longHair', 'headwear', 'facialHair'],
        },
        {
            id: 128,
            name: 'Twitch',
            image: 'leagueoflegends/TwitchSquare.webp',
            tags: ['M', 'rat', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'zaun', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'redEyes', 'whiteHair', 'shortHair', 'mask', 'animal'],
        },
        {
            id: 129,
            name: 'Udyr',
            image: 'leagueoflegends/UdyrSquare.webp',
            tags: ['M', 'human', 'freljord', 'ionia', 'fighter', 'jungle', 'melee', 'mana', 'AD', 'blueEyes', 'brownHair', 'longHair', 'facialHair', 'headwear'],
        },
        {
            id: 130,
            name: 'Urgot',
            image: 'leagueoflegends/UrgotSquare.webp',
            tags: ['M', 'human', 'noxus', 'zaun', 'fighter', 'top', 'ranged', 'mana', 'AD', 'blueEyes', 'bald', 'mask', 'robot'],
        },
        {
            id: 131,
            name: 'Varus',
            image: 'leagueoflegends/VarusSquare.webp',
            tags: ['M', 'darkin', 'demonDarkinSpirit', 'noxus', 'shurima', 'marksman', 'bot', 'ranged', 'mana', 'AP', 'AD', 'Hybrid', 'pinkEyes', 'whiteHair', 'longHair', 'headwear'],
        },
        {
            id: 132,
            name: 'Vayne',
            image: 'leagueoflegends/VayneSquare.webp',
            tags: ['F', 'human', 'demacia', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'purpleHair', 'longHair', 'mask'],
        },
        {
            id: 133,
            name: 'Veigar',
            image: 'leagueoflegends/VeigarSquare.webp',
            tags: ['M', 'yordle', 'bandlecity', 'mage', 'mid', 'ranged', 'mana', 'AP', 'yellowEyes', 'darkHair', 'shortHair', 'headwear', 'animal'],
        },
        {
            id: 134,
            name: 'Vel Koz',
            image: 'leagueoflegends/VelKozSquare.webp',
            tags: ['M', 'voidborn', 'void', 'runeterra', 'mage', 'support', 'mid', 'ranged', 'mana', 'AP', 'pinkEyes', 'bald', 'animal', 'naked'],
        },
        {
            id: 157,
            name: 'Vex',
            image: 'leagueoflegends/VexSquare.webp',
            tags: ['F', 'yordle', 'bandlecity', 'shadow-isles', 'mage', 'mid', 'ranged', 'mana', 'AP', 'pinkEyes', 'greenHair', 'mediumHair', 'headwear', 'animal'],
        },
        {
            id: 135,
            name: 'Vi',
            image: 'leagueoflegends/ViSquare.webp',
            tags: ['F', 'human', 'piltover', 'fighter', 'jungle', 'melee', 'mana', 'AD', 'blueEyes', 'pinkHair', 'mediumHair', 'mask'],
        },
        {
            id: 136,
            name: 'Viego',
            image: 'leagueoflegends/ViegoSquare.webp',
            tags: ['M', 'undead', 'shadow-isles', 'camavor', 'icathiaKathkanCamavor', 'fighter', 'jungle', 'melee', 'mana', 'AD', 'greenEyes', 'whiteHair', 'mediumHair', 'headwear'],
        },
        {
            id: 137,
            name: 'Viktor',
            image: 'leagueoflegends/ViktorSquare.webp',
            tags: ['M', 'human', 'piltover', 'zaun', 'mage', 'mid', 'ranged', 'mana', 'AP', 'orangeEyes', 'brownHair', 'mediumHair', 'headwear', 'mask', 'robot'],
        },
        {
            id: 138,
            name: 'Vladimir',
            image: 'leagueoflegends/VladimirSquare.webp',
            tags: ['M', 'human', 'noxus', 'mage', 'mid', 'ranged', 'health', 'otherResource', 'AP', 'redEyes', 'whiteHair', 'longHair'],
        },
        {
            id: 139,
            name: 'Volibear',
            image: 'leagueoflegends/VolibearSquare.webp',
            tags: ['M', 'god', 'godCelestialAspectAscended', 'freljord', 'tank', 'jungle', 'top', 'melee', 'fury', 'otherResource', 'AD', 'blueEyes', 'whiteHair', 'mediumHair', 'headwear', 'facialHair', 'animal', 'naked'],
        },
        {
            id: 140,
            name: 'Warwick',
            image: 'leagueoflegends/WarwickSquare.webp',
            tags: ['M', 'human', 'zaun', 'fighter', 'jungle', 'melee', 'manaless', 'AD', 'redEyes', 'greenHair', 'mediumHair', 'headwear', 'animal'],
        },
        {
            id: 141,
            name: 'Wukong',
            image: 'leagueoflegends/WukongSquare.webp',
            tags: ['M', 'vastaya', 'ionia', 'fighter', 'top', 'melee', 'mana', 'AD', 'greenEyes', 'brownHair', 'mediumHair', 'animal', 'facialHair'],
        },
        {
            id: 142,
            name: 'Xayah',
            image: 'leagueoflegends/XayahSquare.webp',
            tags: ['F', 'vastaya', 'ionia', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'orangeEyes', 'redHair', 'mediumHair', 'headwear', 'animal'],
        },
        {
            id: 143,
            name: 'Xerath',
            image: 'leagueoflegends/XerathSquare.webp',
            tags: ['M', 'ascended', 'godCelestialAspectAscended', 'shurima', 'mage', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'bald', 'naked'],
        },
        {
            id: 144,
            name: 'Xin Zhao',
            image: 'leagueoflegends/Xin_ZhaoSquare.webp',
            tags: ['M', 'human', 'ionia', 'noxus', 'demacia', 'fighter', 'jungle', 'melee', 'mana', 'AD', 'brownEyes', 'brownHair', 'longHair'],
        },
        {
            id: 145,
            name: 'Yasuo',
            image: 'leagueoflegends/YasuoSquare.webp',
            tags: ['M', 'human', 'ionia', 'fighter', 'mid', 'melee', 'flow', 'otherResource', 'AD', 'brownEyes', 'brownHair', 'longHair'],
        },
        {
            id: 146,
            name: 'Yone',
            image: 'leagueoflegends/YoneSquare.webp',
            tags: ['M', 'undead', 'ionia', 'fighter', 'mid', 'melee', 'manaless', 'AD', 'blueEyes', 'darkHair', 'longHair', 'headwear'],
        },
        {
            id: 147,
            name: 'Yorick',
            image: 'leagueoflegends/YorickSquare.webp',
            tags: ['M', 'human', 'shadow-isles', 'fighter', 'top', 'melee', 'mana', 'AD', 'blueEyes', 'headwear'],
        },
        {
            id: 148,
            name: 'Yuumi',
            image: 'leagueoflegends/YuumiSquare.webp',
            tags: ['F', 'cat', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'bandlecity', 'support', 'ranged', 'mana', 'AP', 'blueEyes', 'blueHair', 'shortHair', 'headwear', 'animal', 'naked'],
        },
        {
            id: 149,
            name: 'Zac',
            image: 'leagueoflegends/ZacSquare.webp',
            tags: ['M', 'golem', 'brackernTitanYetiTrollMinotaurRatCatTreeGolemDragon', 'zaun', 'tank', 'jungle', 'melee', 'health', 'otherResource', 'AP', 'yellowEyes', 'bald', 'naked'],
        },
        {
            id: 150,
            name: 'Zed',
            image: 'leagueoflegends/ZedSquare.webp',
            tags: ['M', 'human', 'ionia', 'assassin', 'mid', 'melee', 'energy', 'AD', 'redEyes', 'whiteHair', 'shortHair', 'headwear', 'mask'],
        },
        {
            id: 158,
            name: 'Zeri',
            image: 'leagueoflegends/ZeriSquare.webp',
            tags: ['F', 'human', 'zaun', 'marksman', 'bot', 'ranged', 'mana', 'AD', 'yellowEyes', 'greenHair', 'longHair'],
        },
        {
            id: 151,
            name: 'Ziggs',
            image: 'leagueoflegends/ZiggsSquare.webp',
            tags: ['M', 'yordle', 'piltover', 'bandlecity', 'mage', 'mid', 'bot', 'ranged', 'mana', 'AP', 'greenEyes', 'blondeHair', 'shortHair', 'headwear', 'animal', 'mask'],
        },
        {
            id: 152,
            name: 'Zilean',
            image: 'leagueoflegends/ZileanSquare.webp',
            tags: ['M', 'human', 'icathia', 'icathiaKathkanCamavor', 'support', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'blueHair', 'longHair'],
        },
        {
            id: 153,
            name: 'Zoe',
            image: 'leagueoflegends/ZoeSquare.webp',
            tags: ['F', 'aspect', 'godCelestialAspectAscended', 'targon', 'mage', 'mid', 'ranged', 'mana', 'AP', 'blueEyes', 'purpleEyes', 'blondeHair', 'purpleHair', 'longHair'],
        },
        {
            id: 154,
            name: 'Zyra',
            image: 'leagueoflegends/ZyraSquare.webp',
            tags: ['F', 'ixtal', 'mage', 'support', 'ranged', 'mana', 'AP', 'orangeEyes', 'redHair', 'longHair', 'naked'],
        },
    ];

    charactersTemp.forEach(character => {
        character.isHidden = false;
    });

    return charactersTemp;
}
