export async function getCharactersFromDatabase() {
    // Cconst characters = await prisma.character.findMany({})
    const charactersTemp = [
        {
            id: 1,
            name: 'Gandalf the gray',
            image: 'gandalf.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'gray',
            eyes: 'blue',
            facialHair: true,
            mustache: true,
            beard: true,
            hat: true,
            glasses: false,
        },
        {
            id: 2,
            name: 'Frodo',
            image: 'frodo.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'short',
            hairColor: 'brown',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 3,
            name: 'Sam',
            image: 'sam.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'short',
            hairColor: 'brown',
            eyes: 'brown',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 4,
            name: 'Aragorn',
            image: 'aragorn.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'brown',
            eyes: 'brown',
            facialHair: true,
            mustache: true,
            beard: true,
            hat: false,
            glasses: false,
        },
        {
            id: 5,
            name: 'Galadriel',
            image: 'galadriel.webp',
            gender: 'F',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'white',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 6,
            name: 'Arwen',
            image: 'arwen.webp',
            gender: 'F',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'brown',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 7,
            name: 'Legolas',
            image: 'legolas.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'white',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 8,
            name: 'Gimli',
            image: 'gimli.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'brown',
            eyes: 'brown',
            facialHair: true,
            mustache: true,
            beard: true,
            hat: true,
            glasses: false,
        },
        {
            id: 9,
            name: 'Gollum',
            image: 'gollum.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'bald',
            hairColor: 'none',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 10,
            name: 'Boromir',
            image: 'boromir.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'short',
            hairColor: 'brown',
            eyes: 'brown',
            facialHair: true,
            mustache: true,
            beard: true,
            hat: false,
            glasses: false,
        },
        {
            id: 11,
            name: 'Elrond',
            image: 'elrond.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'brown',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 12,
            name: 'Eowyn',
            image: 'eowyn.webp',
            gender: 'F',
            skinColor: 'white',
            hair: 'long',
            hairColor: 'white',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
        {
            id: 13,
            name: 'Bilbo (old)',
            image: 'bilbo.webp',
            gender: 'M',
            skinColor: 'white',
            hair: 'short',
            hairColor: 'white',
            eyes: 'blue',
            facialHair: false,
            mustache: false,
            beard: false,
            hat: false,
            glasses: false,
        },
    ];

    charactersTemp.forEach(character => {
        character.isHidden = false;
    });
    console.log(charactersTemp);

    return charactersTemp;
}
